export const REGISTER_AUTH = "REGISTER_AUTH";
export const LOGIN_AUTH = "LOGIN_AUTH";
export const LOG_OUT="LOG_OUT";
export const USERS="USERS";
export const REGISTER_BEGIN="REGISTER_BEGIN";
export const REGISTER_FAILED="REGISTER_FAILED";
export const PRODUCTS="PRODUCTS";
export const SET_ROLE = "SET_ROLE";
export const CART_ADD_PRODUCT = "CART_ADD_PRODUCT";
export const CART_REMOVE_PRODUCT = "CART_REMOVE_PRODUCT";
export const CART_LOAD_PRODUCT = "CART_LOAD_PRODUCT";

